version: "3.8"
services:
  back:
    build:
      context: .
    depends_on:
      - db
    environment:
      POSTGRES_USERNAME: onga
      POSTGRES_PASSWORD: onga
      POSTGRES_DB: onga
      POSTGRES_DB_URL: db
    volumes:
      - files:/srv/public
    ports:
      - "4664:4664"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: onga
      POSTGRES_PASSWORD: onga
      POSTGRES_DB: onga
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onga"]
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - "4666:5432"
volumes:
  db:
  files: